---

- name: Copy-over files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ mcs_path }}/{{ item }}'
    mode: 0644
  with_items:
    - eula.txt
    - server.properties
    - whitelist.json
  become: true
  become_user: '{{ mcs_user }}'