---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mcs_user }}"
    group: "{{ mcs_user }}"
    mode: "0755"
  with_items:
    - "{{ mcs_path }}"
    - "{{ mcs_path }}/plugins"
    - "{{ mcs_path }}/build"
  become: true

- name: Check server exists
  stat:
    path: "{{ mcs_path }}/spigot-{{ mcs_version }}.jar"
  register: server_jar_stat

- name: Delete build dir
  file:
    state: absent
    path: "{{ mcs_path }}/build"
  when: not server_jar_stat.stat.exists

- name: Create build directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mcs_user }}"
    group: "{{ mcs_user }}"
    mode: "0755"
  with_items:
    - "{{ mcs_path }}/build"
  become: true
  when: not server_jar_stat.stat.exists

- name: Download spigot
  ansible.builtin.get_url:
    url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    dest: "{{ mcs_path }}/build/"
    mode: "0644"
  become: true
  become_user: "{{ mcs_user }}"
  when: not server_jar_stat.stat.exists

- name: Build spigot
  shell: "cd {{ mcs_path }}/build && java -jar BuildTools.jar --rev {{ mcs_version }}"
  become: true
  become_user: "{{ mcs_user }}"
  when: not server_jar_stat.stat.exists

- name: Copy spigot
  ansible.builtin.copy:
    src: "{{ mcs_path }}/build/spigot-{{ mcs_version }}.jar"
    remote_src: true
    dest: "{{ mcs_path }}/spigot-{{ mcs_version }}.jar"
    mode: "0644"
  become: true
  become_user: "{{ mcs_user }}"
  when: not server_jar_stat.stat.exists

- name: Add systemd service
  ansible.builtin.template:
    src: mcs.service
    dest: /lib/systemd/system/mcs.service
    mode: "0644"
  become: true
  notify:
    - Mcs_reload_systemd
    - Mcs_restart