---
- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mcs_user }}"
    group: "{{ mcs_user }}"
    mode: "0755"
  with_items:
    - "{{ mcs_path }}"
  become: true

- name: Check server exists
  stat:
    path: "{{ mcs_path }}/run.sh"
  register: server_build_stat

- name: Download forge
  ansible.builtin.get_url:
    url: "https://maven.minecraftforge.net/net/minecraftforge/forge/{{ forge_version }}/forge-{{ forge_version }}-installer.jar"
    dest: "{{ mcs_path }}"
    mode: "0644"
  become: true
  become_user: "{{ mcs_user }}"
  when: not server_build_stat.stat.exists

- name: Build forge
  shell: "cd {{ mcs_path }} && java -jar forge-{{ forge_version }}-installer.jar --installServer"
  become: true
  become_user: "{{ mcs_user }}"
  when: not server_build_stat.stat.exists

- name: Copy-over files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ mcs_path }}/{{ item }}"
    mode: 0644
  with_items:
    - eula.txt
    - server.properties
    - whitelist.json
    - user_jvm_args.txt
  become: true
  become_user: "{{ mcs_user }}"

- name: Add systemd service
  ansible.builtin.template:
    src: mcs.service
    dest: /lib/systemd/system/mcs.service
    mode: "0644"
  become: true
  notify:
    - Mcs_reload_systemd
    - Mcs_restart
